from enum import Enum

class Grade(str, Enum):
    GRADE_5 = "5th grade"
    GRADE_6 = "6th grade"
    GRADE_7 = "7th grade"
    GRADE_8 = "8th grade"
    GRADE_9 = "9th grade"
    GRADE_10 = "10th grade"
    GRADE_11 = "11th grade"
    GRADE_12 = "12th grade"
    COLLEGE_FRESHMAN = "College Freshman"
    COLLEGE_SOPHOMORE = "College Sophomore"
    COLLEGE_JUNIOR = "College Junior"
    COLLEGE_SENIOR = "College Senior"
    GRADUATE_STUDENT = "Graduate Student"
    HIGH_SCHOOL_FRESHMAN = "High School Freshman"
    HIGH_SCHOOL_SOPHOMORE = "High School Sophomore"
    HIGH_SCHOOL_JUNIOR = "High School Junior"
    HIGH_SCHOOL_SENIOR = "High School Senior"
    COLLEGE_UNDERGRADUATE = "College Undergraduate"
    GRADUATE_SCHOOL = "Graduate School"
    WORKING_PROFESSIONAL = "Graduated / Working Professional"

class Ethnicity(str, Enum):
    SOUTH_ASIAN = "South Asian: Includes Indian, Pakistan, Sri Lankan, Bangaladesh"
    BLACK_AFRICAN_AMERICAN = "Black or African American: Includes Jamaican, Nigerian, Haitian, and Ethiopian"
    WHITE_EUROPEAN = "White or European: Includes German, Irish, English, Italian, Polish, and French"
    HISPANIC_LATINO = "Hispanic or Latino: Includes Puerto Rican, Mexican, Cuban, Salvadoran, and Colombian"
    MIDDLE_EASTERN_NORTH_AFRICAN = "Middle Eastern or North African: Includes Lebanese, Iranian, Egyptian, Moroccan, Israeli, and Palestinian"
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER = "Native Hawaiian or Pacific Islander: Includes Samoan, Buamanian, Chamorro, and Tongan"
    AMERICAN_INDIAN_ALASKA_NATIVE = "American Indian or Alaska Native"
    ASIAN = "Asian: Includes Chinese, Japanese, Filipino, Korean, South Asian, and Vietnamese"

class Preference(str, Enum):
    PREFER_ONLY = "Prefer ONLY to be matched within that similarity"
    PREFER_IT = "Prefer it, but available to others as needed"
    PREFER_NOT = "Prefer NOT to be matched within that similarity"
    NO_PREFERENCE = "Do not have a preference. Either is fine."
    OTHER = "Other:"

class Gender(str, Enum):
    CIS_MALE = "Cisgender Male"
    CIS_FEMALE = "Cisgender Female"
    TRANS_MALE = "Transgender Male"
    TRANS_FEMALE = "Transgender Female"
    PREFER_NOT_DISCLOSE = "Prefer not to disclose"
    OTHERS = "Others"

class SessionType(str, Enum):
    HOMEWORK_HELP = "Homework Help"
    EXPOSURE_STEAM = "Exposure to STEAM in general"
    COLLEGE_GUIDANCE = "College guidance"
    CAREER_GUIDANCE = "Career guidance"
    EXPLORE_FIELD = "Explore a particular field"

class Method(str, Enum):
    WEB_CONFERENCE = "Web conference (ie. Zoom video conference)"
    IN_PERSON = "In person"
    HYBRID = "Hybrid (both web and in person)"
    OTHER = "Other:"

class TimeSlot(Enum):
    MONDAY_7_9 = "Monday-7am to 9am"
    MONDAY_9_11 = "Monday-9am to 11am"
    MONDAY_11_1 = "Monday-11am to 1pm"
    MONDAY_1_3 = "Monday-1pm to 3pm"
    MONDAY_3_5 = "Monday-3pm to 5pm"
    MONDAY_5_7 = "Monday-5pm to 7pm"
    MONDAY_7_9 = "Monday-7pm to 9pm"
    TUESDAY_7_9 = "Tuesday-7am to 9am"
    TUESDAY_9_11 = "Tuesday-9am to 11am"
    TUESDAY_11_1 = "Tuesday-11am to 1pm"
    TUESDAY_1_3 = "Tuesday-1pm to 3pm"
    TUESDAY_3_5 = "Tuesday-3pm to 5pm"
    TUESDAY_5_7 = "Tuesday-5pm to 7pm"
    TUESDAY_7_9 = "Tuesday-7pm to 9pm"
    WEDNESDAY_7_9 = "Wednesday-7am to 9am"
    WEDNESDAY_9_11 = "Wednesday-9am to 11am"
    WEDNESDAY_11_1 = "Wednesday-11am to 1pm"
    WEDNESDAY_1_3 = "Wednesday-1pm to 3pm"
    WEDNESDAY_3_5 = "Wednesday-3pm to 5pm"
    WEDNESDAY_5_7 = "Wednesday-5pm to 7pm"
    WEDNESDAY_7_9 = "Wednesday-7pm to 9pm"
    THURSDAY_7_9 = "Thursday-7am to 9am"
    THURSDAY_9_11 = "Thursday-9am to 11am"
    THURSDAY_11_1 = "Thursday-11am to 1pm"
    THURSDAY_1_3 = "Thursday-1pm to 3pm"
    THURSDAY_3_5 = "Thursday-3pm to 5pm"
    THURSDAY_5_7 = "Thursday-5pm to 7pm"
    THURSDAY_7_9 = "Thursday-7pm to 9pm"
    FRIDAY_7_9 = "Friday-7am to 9am"
    FRIDAY_9_11 = "Friday-9am to 11am"
    FRIDAY_11_1 = "Friday-11am to 1pm"
    FRIDAY_1_3 = "Friday-1pm to 3pm"
    FRIDAY_3_5 = "Friday-3pm to 5pm"
    FRIDAY_5_7 = "Friday-5pm to 7pm"
    FRIDAY_7_9 = "Friday-7pm to 9pm"
    SATURDAY_7_9 = "Saturday-7am to 9am"
    SATURDAY_9_11 = "Saturday-9am to 11am"
    SATURDAY_11_1 = "Saturday-11am to 1pm"
    SATURDAY_1_3 = "Saturday-1pm to 3pm"
    SATURDAY_3_5 = "Saturday-3pm to 5pm"
    SATURDAY_5_7 = "Saturday-5pm to 7pm"
    SATURDAY_7_9 = "Saturday-7pm to 9pm"
    SUNDAY_7_9 = "Sunday-7am to 9am"
    SUNDAY_9_11 = "Sunday-9am to 11am"
    SUNDAY_11_1 = "Sunday-11am to 1pm"
    SUNDAY_1_3 = "Sunday-1pm to 3pm"
    SUNDAY_3_5 = "Sunday-3pm to 5pm"
    SUNDAY_5_7 = "Sunday-5pm to 7pm"
    SUNDAY_7_9 = "Sunday-7pm to 9pm"